const data = {
  products: [
    {
      _id:"1",
      category:"Ram",
      name :"Corsair Vengeance LPX DDR4 3200 PC4-25600 16GB 2X8GB CL16 Negro",
      slug: "Corsair-Vengeance-LPX DDR4-3200-PC4-25600-16GB-2X8GB-CL16-Negro",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/26/262822/corsair-vengeance-lpx-ddr4-3200-pc4-25600-16gb-2x8gb-cl16-negro.jpg",
          price:"50",
          countInStock:20,
          brand: "Corsair",
          rating:4.5,
          numReviews:10,
          description:"La memoria Corsair Vengeance LPX se ha diseñado para overclocking de alto rendimiento. El disipador de calor, fabricado en aluminio puro, permite una disipación térmica más rápida, la placa impresa de ocho capas administra el calor y proporciona una capacidad superior para incrementar el overclocking",
            
    },
    {
      _id:"2",
      category:"Ram",
      name :"Corsair Vengeance LPX DDR4 3200MHz PC4-25600 32GB 2x16GB CL16",
      slug: "Corsair-Vengeance-LPX-DDR4-3200MHz-PC4-25600-32GB-2x16GB-CL16",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/26/262822/corsair-vengeance-lpx-ddr4-3200-pc4-25600-16gb-2x8gb-cl16-negro.jpg",
          price:"90",
          countInStock:10,
          brand: "Corsair",
          rating:5,
          numReviews:5,
          description:"La memoria VENGEANCE LPX está diseñada para overclocking de alto rendimiento. El disipador térmico está hecho de aluminio puro para una disipación de calor más rápida, y el PCB de ocho capas ayuda a controlar el calor y proporciona un margen superior de overclocking superior.",
            
    },
    {
      _od:"3",
      category:"Ram",
      name :"Kingston FURY Beast DDR4 3200 MHz 16GB 2x8GB CL16",
      slug: "Kingston-FURY-Beast-DDR4-3200-MHz-16GB-2x8GB-CL16",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/43/432664/1392-kingston-fury-beast-ddr4-3200-mhz-16gb-2x8gb-cl16.jpg",
          price:"42",
          countInStock:15,
          brand: "Kingston ",
          rating:3.5,
          numReviews:7,
          description:"La memoria para PC FURY Beast DDR4 de Kingston ofrece un potente aumento de rendimiento para juegos, edición de vídeo y renderización con velocidades de hasta 3733 MHz. Esta rentable actualización está disponible en velocidades de 2666 MHz a 3733 MHz, con latencias de CL15 a 19, capacidades de 4 GB a 32 GB en módulos individuales y de 8 GB a 128 GB en kits. Su overclocking automático Plug N Play a velocidades de 2666 MHz está disponible en Intel XMP y Ryzen. El módulo FURY Beast DDR4 se mantiene fresco gracias a su elegante y delgado disipador de calor. Probada al 100% y garantizada de por vida, esta actualización es muy fácil y sin problemas para tu sistema Intel o AMD.",
            
    },
    {
      _id:"4",
      category:"Ram",
      name :"Kingston FURY Beast DDR4 3200 MHz 8GB CL16",
      slug: "Kingston-FURY-Beast-DDR4-3200-MHz-8GB-CL16",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/43/432662/1958-kingston-fury-beast-ddr4-3200-mhz-8gb-cl16.jpg",
          price:"40",
          countInStock:5,
          brand: "Kingston",
          rating:4,
          numReviews:10,
          description:"La memoria FURY Beast DDR4 de Kingston es la elección perfecta para los desarrolladores de sistemas y para quienes buscan una actualización para regenerar un sistema lento. La memoria DDR4 FURY Beast de Kingston, que ofrece una actualización Plug N Play sencilla y fácil, hará un overclocking automático a la velocidad más alta permitida por el BIOS de tu sistema (hasta 2666 MHz).",
            
    },
    {
      _id:"5",
      category:"Towers",
      name :"Tempest Spectra RGB Torre ATX Blanca",
      slug: "Tempest-Spectra-RGB-Torre-ATX-Blanca",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/22/222326/photo-3.jpg",
          price:"60",
          countInStock:15,
          brand: "Tempest",
          rating:3,
          numReviews:15,  
          description:"Tempest expande su familia de torres, lanzando la versión blanca de su éxito de ventas: Tempest Spectra RGB, una caja modelo ATX con efectos de retroiluminación tanto en el frontal como en su ventilador trasero que hará las delicias tanto de aquellos que acaban de llegar al mundo gaming como de los harcore gamers.",
            
    },
    {
      _id:"6",
      category:"Towers",
      name :"Tempest Spectra RGB Torre ATX Blanca",
      slug: "Tempest-Spectra-RGB-Torre-ATX-Blanca",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/22/222326/photo-3.jpg",
          price:"60",
          countInStock:15,
          brand: "Tempest",
          rating:3,
          numReviews:15,
          description:"Tempest expande su familia de torres, lanzando la versión blanca de su éxito de ventas: Tempest Spectra RGB, una caja modelo ATX con efectos de retroiluminación tanto en el frontal como en su ventilador trasero que hará las delicias tanto de aquellos que acaban de llegar al mundo gaming como de los harcore gamers.",
            
    },
    {
_id:"7",
      category:"Towers",
      name :"MSI MAG FORGE M100R Cristal Templado USB 3.2 ARGB Negra",
      slug: "MSI-MAG-FORGE-M100R-Cristal-Templado-USB-3.2-ARGB-Negra",
          image:"https://thumb.pccomponentes.com/w-530-530/articles/1040/10405218/1401-msi-mag-forge-m100r-cristal-templado-usb-32-argb-negra.jpg",
          price:"80",
          countInStock:15,
          brand: "Msi",
          rating:4.5,
          numReviews:10,
          description:"La nueva MSI M100R puede incorporar hasta 6 ventiladores de sistema, proporcionando ventilación y rendimiento estable a todo el sistema. Además, con su panel lateral de cristal templado podrás ver el interior de tu configuración gaming y disfrutar con los efectos ARGB de sus ventiladores incorporados pulsando un solo botón. ",
            
    },
    
   
  ],
};
export default data;